### PR TITLE
Add tvOS and watchOS deployment targets

### PR DESCRIPTION
**Pull request by thebarndog**
## Obligatory Office GIF

dxocwugdzryg4

## What

Adds tvOS and watchOS targets and made the schemes shared so Carthage can access them. Also added deployment targets to the podspec

## The Why

TL;DR I was working on this: https://github.com/feathersjs-ecosystem/feathers-swift/pull/29 and saw this awesome library but it didn't have tvOS/watchOS support for Carthage so I added it! But also because **I said so!**

## Pending

One other change I'd like to see/might put a PR up for is adding testing targets for each deployment target. They'd all point to the same testing bundle and they'd let each scheme run the tests themselves which ensures tests pass on any given OS. And also Linux support would be cool, down to put a PR up for that as well.

### CODE REVIEW

**Comment by khanlou** [comment]
This is cool, thanks for the pull request. How does this change the process for various types of changes we might make in the future? For example, if there's a new file, what do I need to do to make sure this doesn't break?

**Comment by thebarndog** [comment]
I think all you'd have to do is make sure that the file is added to each target. If you add test targets for each framework target so that its a 1:1 ratio (where each test target points to the same test bundle), then if you forget to add a file to a particular build target, those tests should fail. I can do that in another PR if you'd like.

The way I do it is a bit roundabout and you do end up with 8 targets to manage vs two but I find it's a bit more explicit and easier to keep track of when each target is designated for a particular OS.

**Comment by thebarndog** [comment]
I'm working on a framework scaffolding tool too, won't be done for a while, but that should ease the pain of manually setting up the targets individually which is probably the biggest pain, along with the manual steps of integrating Carthage

**Comment by khanlou** [comment]
Okay, I'm going to go ahead and merge this. Might ping you from time to time if there's an issue with it. Open to PRs for linux and other platform tests too.

**Comment by thebarndog** [comment]
Definitely! My email is on my profile so I don't respond to notifications (which happens a lot) you can use that if something urgent/extraneous comes up. I'm using this library too for the next version of Feathers Swift so I might uncover a thing or two.

**Pull request merged**
