### PR TITLE
Add a Travis build job for osx_image xcode9.2.

### LINKED ISSUE #47: Add Xcode 9.2 deployment in Travis CI.
As a response to issues discussed in #45.

### PR DESCRIPTION
**Pull request by isaac-weisberg**
Resolves #47.

### CODE REVIEW

**Comment by isaac-weisberg** [comment]
See?
But once #46 is merged, this same check should pass.

**Comment by khanlou** [comment]
@isaac-weisberg can you update this with master and ensure that travis now passes?

**Comment by khanlou** [comment]
@isaac-weisberg looks like it's working now, can i merge this?

**Comment by isaac-weisberg** [comment]
@khanlou yes, please do merge, I am yet to come up with a proper solution to test 2 versions on Linux, yet, it just doesn't work. Thank you.

**Comment by khanlou** [comment]
either way, we still don't have a release for 4.1 yet, so there's some time

**Pull request merged**
