### PR TITLE
Fix Xcode 9.3 warnings

### PR DESCRIPTION
**Pull request by MrNickBarker**

### CODE REVIEW

**Comment by khanlou** [comment]
Can you update the travis configuration file to target the new Xcode as well? I think that's why the build is failing.

**Comment by isaac-weisberg** [comment]
So what kind of warnings there were and what they were caused by?

**Comment by isaac-weisberg** [comment]
Evidently, Travis ain't building not because of the Xcode version, but rather because there was a method name change that was not "double tapped". Did this code build on your machine? Are you sure that all files are included in the PR commits?

**Comment by MrNickBarker** [comment]
@isaac-weisberg @khanlou it turns out the issue was with the Travis configuration. 

Xcode 9.3 image is still not available on Travis, so it's using the beta version for now.

**Comment by khanlou** [comment]
🎉

**Review by khanlou — APPROVED** [review]

**Comment by isaac-weisberg** [comment]
Yeah, they really have done deprecated `flatMap` method in favor of `compactMap`.

Though.
https://developer.apple.com/documentation/swift/array/2957701-compactmap

One could refer to this little thing and note that tiny little SDK section at top right and see that `Xcode 9.3+` is written in there. Question to everyone, including @khanlou:
So you sure this will build on Xcode versions like 9.2 and below? And Swift 4.0.x?

It does slightly look that this #43 has just annihilated all backwards compatibility with projects that don't user Apple's latest tools.

**Pull request merged**
